stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  only:
    - master
  script:
    - make
  image: registry.gitlab.com/coldfusionjp/gitlab-ci:latest
  services:
    - docker:dind
  tags:
    - linux-runner

test:
  stage: test
  only:
    - master
  script:
    - make test
  image: registry.gitlab.com/coldfusionjp/gitlab-ci:latest
  tags:
    - linux-runner
