stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

build:
  stage: build
  only:
    - master
  cache:
    paths:
      - build/
  script:
    - make
    - make test
  image: registry.gitlab.com/coldfusionjp/gitlab-ci:latest
  services:
    - docker:dind
  tags:
    - linux-runner
